version: '3.4' # docker compose version

services:
  test-promp-server:
    build:
      context: .
      dockerfile: ${PWD}/Dockerfile
    container_name: test-prompt
    # image: $IMAGE_NAME
    # volumes:
      # - ~/translator-central-ai-logs/:/app/logs
    working_dir: /app
    entrypoint: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    restart: always
    