"""Initial migration

Revision ID: 38e70daf3c49
Revises: 623dc1b3a70f
Create Date: 2023-05-08 10:21:17.429867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e70daf3c49'
down_revision = '623dc1b3a70f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('prompt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'prompt')
    # ### end Alembic commands ###
