"""Initial migration

Revision ID: 623dc1b3a70f
Revises: e0eeef0f1aeb
Create Date: 2023-05-08 09:52:52.250596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623dc1b3a70f'
down_revision = 'e0eeef0f1aeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('vocabulary', sa.String(), nullable=True))
    op.add_column('users', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_id')
    op.drop_column('courses', 'vocabulary')
    # ### end Alembic commands ###
