"""Initial migration

Revision ID: 7dfa9ec5771d
Revises: f394a16077bb
Create Date: 2023-05-08 12:01:25.165664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dfa9ec5771d'
down_revision = 'f394a16077bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('essay', sa.String(), nullable=True))
    op.drop_column('users', 'eassy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('eassy', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'essay')
    # ### end Alembic commands ###
