"""Initial migration

Revision ID: e0eeef0f1aeb
Revises: 930fd10634dd
Create Date: 2023-05-08 09:48:20.457479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0eeef0f1aeb'
down_revision = '930fd10634dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
