"""Initial migration

Revision ID: f394a16077bb
Revises: 38e70daf3c49
Create Date: 2023-05-08 11:12:30.633838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f394a16077bb'
down_revision = '38e70daf3c49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('gram', sa.String(), nullable=True))
    op.drop_column('courses', 'pram')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('pram', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('courses', 'gram')
    # ### end Alembic commands ###
